### ISSUE TITLE
API returns 500 when duplicate permalink provided

### ISSUE THREAD

**Issue by tobias-g1** [travelfeed-io/travelfeed-io#114] opened 2019-07-06 17:16 UTC
**Describe the bug**

If you attempt to create a post with the same title and therefore the same permlink the post cannot be submitted due to broadcast errors.

**To Reproduce**

1. Go to the create post within travel feed.
2. Enter a title that you have used previously on another post (the post should not have the parent permlink of "travelfeed", therefore it should have been created on another front end.
3. Enter any post body that meets the validation of 250 words.
4. Publish the post
5. Note that the post cannot be created. 

**Expected behavior**
When a user creates that has the same title that was previously used on another post, the permlink that is created from the title should be adjusted to make it unique.

**Error in Console**

<img width="1425" alt="DevTools_-_travelfeed_io_dashboard_publish_and_TravelBlog__Publish_-_TravelFeed__The_Travel_Community" src="https://user-images.githubusercontent.com/17148879/60759220-4f812100-a019-11e9-951b-5683d615b509.png">

```
error: "server_error"
error_description: "equal( com.parent_permlink, o.parent_permlink ): The permlink of a comment cannot change."
```

**Request Payload**

```
{
   "operations":[
      [
         "comment",
         {
            "parent_author":"",
            "parent_permlink":"travelfeed",
            "author":"votezilla",
            "permlink":"test",
            "title":"Test",
            "body":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed arcu interdum, luctus augue eget, rhoncus turpis. Etiam id erat non metus mattis pellentesque nec non ante. Nunc eu tristique risus, eget consequat turpis. Cras iaculis sodales justo consequat faucibus. Etiam suscipit vitae risus et gravida.",
            "json_metadata":"{\"tags\":[\"travelfeed\"],\"app\":\"travelfeed/1.0.0\",\"community\":\"travelfeed\",\"image\":[],\"links\":[],\"users\":[]}"
         }
      ]
   ]
}

```

Note: The permlink of "test" as mentioned in the payload was previously used. 

**Solution**

Prior the broadcast add a middleware that checks that if a user a permalink exists, in the event that it does exist, a random string could be appended to the post to make it unique. In the event, it doesn't exist no change is required.

**Comment by tiotdev** [comment] 2019-07-07 08:53
Thanks for this bug report.

However, I cannot reproduce this. If I try to write a new post with a title/permlink that does exist, there is no exception, but the old post is edited with the new content, which is also not the intended behaviour. Your solution will fix both these issues.

**Comment by tobias-g1** [comment] 2019-07-07 11:15
Ahh okay, I missed something here, by any chance did you edit something that previously had the parent_permlink of "travelfeed" and therefore it was okay to edit it, in my steps I was potentially editing something where I was trying to adjust the parent_permlink.

**Comment by tiotdev** [comment] 2019-07-07 12:02
You are right. Actually, the same bug appears when trying to edit posts that have a parent_permlink !== "travelfeed", which can happen if they were published through another dApp. Thank you!

**Comment by tiotdev** [comment] 2019-08-05 22:23
Fixed in https://github.com/travelfeed-io/travelfeed-io/commit/23538d49cf1c91b4a5ce41f3c991fc3dc71cfef8
Will be merged into master later this week

**Closed by tiotdev** 2019-08-05 22:23 UTC
Labels: bug
